# @package env
short_name: cube-triple
name: cube-triple-play-v0
source_name: cube-triple-play-v0
dataset_kind: standard
dataset_dir: ${oc.env:TREEWM_DATA_ROOT,/lustre/fs11/portfolios/edgeai/projects/edgeai_tao-ptm_image-foundation-model-clip/users/chrislin/datasets/ogbench-rql-50task}/standard
obs_dim: 46
action_dim: 5
xy_dims: [19, 20, 21, 28, 29, 30, 37, 38, 39]
max_episode_steps: 1000
relative_endpoints: true
