# @package env
short_name: scene
name: scene-play-v0
source_name: scene-play-v0
dataset_kind: standard
dataset_dir: ${oc.env:TREEWM_DATA_ROOT,/lustre/fs11/portfolios/edgeai/projects/edgeai_tao-ptm_image-foundation-model-clip/users/chrislin/datasets/ogbench-rql-50task}/standard
obs_dim: 40
action_dim: 5
xy_dims: [19, 20, 21, 28, 29, 32, 33, 36, 38]
max_episode_steps: 750
relative_endpoints: false
